// Popup JavaScript (compiled from popup.ts)
// This will be generated by the build process

// For now, we'll create a simple version that works without compilation

const DEFAULT_PREFERENCES = {
  bedrooms: null,
  purchasePrice: null,
  downPaymentPercent: 20,
  insuranceMonthly: 100,
  hoaMonthly: 0,
  propertyManagementMode: 'percent',
  propertyManagementPercent: 10,
  propertyManagementAmount: 0,
  overrideTaxRate: false,
  overrideMortgageRate: false,
  propertyTaxRateAnnualPct: null,
  mortgageRateAnnualPct: null,
  showBadgeOnAllPages: true,
  badgePosition: 'near-address',
};

async function getPreferences() {
  return new Promise((resolve) => {
    chrome.storage.sync.get(DEFAULT_PREFERENCES, (items) => {
      resolve(items);
    });
  });
}

async function savePreferences(prefs) {
  return new Promise((resolve, reject) => {
    chrome.storage.sync.set(prefs, () => {
      if (chrome.runtime.lastError) {
        reject(new Error(chrome.runtime.lastError.message));
      } else {
        resolve();
      }
    });
  });
}

async function resetPreferences() {
  return savePreferences(DEFAULT_PREFERENCES);
}

async function init() {
  const prefs = await getPreferences();
  
  // Populate form fields
  document.getElementById('down-payment-percent').value = String(prefs.downPaymentPercent);
  document.getElementById('insurance-monthly').value = String(prefs.insuranceMonthly);
  document.getElementById('hoa-monthly').value = String(prefs.hoaMonthly);
  document.getElementById('pm-mode').value = prefs.propertyManagementMode;
  document.getElementById('pm-percent').value = String(prefs.propertyManagementPercent);
  document.getElementById('pm-amount').value = String(prefs.propertyManagementAmount);
  document.getElementById('override-tax-rate').checked = prefs.overrideTaxRate;
  document.getElementById('override-mortgage-rate').checked = prefs.overrideMortgageRate;
  document.getElementById('tax-rate').value = prefs.propertyTaxRateAnnualPct !== null ? String(prefs.propertyTaxRateAnnualPct) : '';
  document.getElementById('mortgage-rate').value = prefs.mortgageRateAnnualPct !== null ? String(prefs.mortgageRateAnnualPct) : '';
  document.getElementById('show-badge-all-pages').checked = prefs.showBadgeOnAllPages;
  document.getElementById('badge-position').value = prefs.badgePosition;
  
  updateConditionalFields();
  
  const form = document.getElementById('settings-form');
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    await saveFormData();
    showMessage('Settings saved!');
  });
  
  const resetBtn = document.getElementById('reset-btn');
  resetBtn.addEventListener('click', async () => {
    if (confirm('Reset all settings to defaults?')) {
      await resetPreferences();
      location.reload();
    }
  });
  
  const pmMode = document.getElementById('pm-mode');
  pmMode.addEventListener('change', updateConditionalFields);
  
  const overrideTax = document.getElementById('override-tax-rate');
  const overrideMortgage = document.getElementById('override-mortgage-rate');
  overrideTax.addEventListener('change', updateConditionalFields);
  overrideMortgage.addEventListener('change', updateConditionalFields);
}

function updateConditionalFields() {
  const pmMode = document.getElementById('pm-mode').value;
  const pmPercentGroup = document.getElementById('pm-percent-group');
  const pmAmountGroup = document.getElementById('pm-amount-group');
  
  if (pmMode === 'percent') {
    pmPercentGroup.style.display = 'block';
    pmAmountGroup.style.display = 'none';
  } else {
    pmPercentGroup.style.display = 'none';
    pmAmountGroup.style.display = 'block';
  }
  
  const overrideTax = document.getElementById('override-tax-rate').checked;
  const overrideMortgage = document.getElementById('override-mortgage-rate').checked;
  const taxRateGroup = document.getElementById('tax-rate-group');
  const mortgageRateGroup = document.getElementById('mortgage-rate-group');
  
  taxRateGroup.style.display = overrideTax ? 'block' : 'none';
  mortgageRateGroup.style.display = overrideMortgage ? 'block' : 'none';
}

async function saveFormData() {
  const prefs = {
    downPaymentPercent: parseFloat(document.getElementById('down-payment-percent').value) || DEFAULT_PREFERENCES.downPaymentPercent,
    insuranceMonthly: parseFloat(document.getElementById('insurance-monthly').value) || DEFAULT_PREFERENCES.insuranceMonthly,
    hoaMonthly: parseFloat(document.getElementById('hoa-monthly').value) || DEFAULT_PREFERENCES.hoaMonthly,
    propertyManagementMode: document.getElementById('pm-mode').value,
    propertyManagementPercent: parseFloat(document.getElementById('pm-percent').value) || DEFAULT_PREFERENCES.propertyManagementPercent,
    propertyManagementAmount: parseFloat(document.getElementById('pm-amount').value) || DEFAULT_PREFERENCES.propertyManagementAmount,
    overrideTaxRate: document.getElementById('override-tax-rate').checked,
    overrideMortgageRate: document.getElementById('override-mortgage-rate').checked,
    propertyTaxRateAnnualPct: document.getElementById('override-tax-rate').checked
      ? parseFloat(document.getElementById('tax-rate').value) || null
      : null,
    mortgageRateAnnualPct: document.getElementById('override-mortgage-rate').checked
      ? parseFloat(document.getElementById('mortgage-rate').value) || null
      : null,
    showBadgeOnAllPages: document.getElementById('show-badge-all-pages').checked,
    badgePosition: document.getElementById('badge-position').value,
  };
  
  await savePreferences(prefs);
}

function showMessage(message) {
  const msg = document.createElement('div');
  msg.textContent = message;
  msg.style.cssText = `
    position: fixed;
    top: 16px;
    right: 16px;
    background: #0a0a0a;
    color: white;
    padding: 8px 16px;
    border-radius: 4px;
    font-size: 12px;
    z-index: 10000;
  `;
  document.body.appendChild(msg);
  setTimeout(() => msg.remove(), 2000);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
