// Popup JavaScript (compiled from popup.ts)
// This will be generated by the build process

// For now, we'll create a simple version that works without compilation

const DEFAULT_PREFERENCES = {
  bedrooms: null,
  purchasePrice: null,
  downPaymentMode: 'percent',
  downPaymentPercent: 20,
  downPaymentAmount: 0,
  insuranceMonthly: 100,
  hoaMonthly: 0,
  propertyManagementMode: 'percent',
  propertyManagementPercent: 10,
  propertyManagementAmount: 0,
  overrideTaxRate: false,
  overrideMortgageRate: false,
  propertyTaxRateAnnualPct: null,
  mortgageRateAnnualPct: null,
  customLineItems: [],
  enabledSites: {
    redfin: true,
    zillow: true,
  },
};

async function getPreferences() {
  return new Promise((resolve) => {
    chrome.storage.sync.get(DEFAULT_PREFERENCES, (items) => {
      resolve(items);
    });
  });
}

async function savePreferences(prefs) {
  return new Promise((resolve, reject) => {
    chrome.storage.sync.set(prefs, () => {
      if (chrome.runtime.lastError) {
        reject(new Error(chrome.runtime.lastError.message));
      } else {
        resolve();
      }
    });
  });
}

async function resetPreferences() {
  return savePreferences(DEFAULT_PREFERENCES);
}

async function init() {
  const prefs = await getPreferences();

  // Populate form fields
  document.getElementById('dp-mode').value = prefs.downPaymentMode || 'percent';
  document.getElementById('down-payment-percent').value = String(prefs.downPaymentPercent);
  document.getElementById('down-payment-amount').value = String(prefs.downPaymentAmount || 0);
  document.getElementById('insurance-monthly').value = String(prefs.insuranceMonthly);
  document.getElementById('hoa-monthly').value = String(prefs.hoaMonthly);
  document.getElementById('pm-mode').value = prefs.propertyManagementMode;
  document.getElementById('pm-percent').value = String(prefs.propertyManagementPercent);
  document.getElementById('pm-amount').value = String(prefs.propertyManagementAmount);
  document.getElementById('override-tax-rate').checked = prefs.overrideTaxRate;
  document.getElementById('override-mortgage-rate').checked = prefs.overrideMortgageRate;
  document.getElementById('tax-rate').value = prefs.propertyTaxRateAnnualPct !== null ? String(prefs.propertyTaxRateAnnualPct) : '';
  document.getElementById('mortgage-rate').value = prefs.mortgageRateAnnualPct !== null ? String(prefs.mortgageRateAnnualPct) : '';
  document.getElementById('enable-redfin').checked = prefs.enabledSites?.redfin !== false;
  document.getElementById('enable-zillow').checked = prefs.enabledSites?.zillow !== false;

  updateConditionalFields();

  // Scroll to override section if overrides are active
  if (prefs.overrideTaxRate || prefs.overrideMortgageRate) {
    setTimeout(() => {
      const overrideSection = document.querySelector('.section.card:has(#override-tax-rate)');
      if (overrideSection) {
        overrideSection.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }, 100);
  }

  const form = document.getElementById('settings-form');
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    await saveFormData();
    showMessage('Settings saved!');
  });

  const resetBtn = document.getElementById('reset-btn');
  resetBtn.addEventListener('click', async () => {
    if (confirm('Reset all settings to defaults?')) {
      await resetPreferences();
      location.reload();
    }
  });

  const dpMode = document.getElementById('dp-mode');
  dpMode.addEventListener('change', updateConditionalFields);

  const pmMode = document.getElementById('pm-mode');
  pmMode.addEventListener('change', updateConditionalFields);

  const overrideTax = document.getElementById('override-tax-rate');
  const overrideMortgage = document.getElementById('override-mortgage-rate');
  overrideTax.addEventListener('change', updateConditionalFields);
  overrideMortgage.addEventListener('change', updateConditionalFields);
}

function updateConditionalFields() {
  const dpMode = document.getElementById('dp-mode').value;
  const dpPercentGroup = document.getElementById('dp-percent-group');
  const dpAmountGroup = document.getElementById('dp-amount-group');

  if (dpMode === 'percent') {
    dpPercentGroup.style.display = 'block';
    dpAmountGroup.style.display = 'none';
  } else {
    dpPercentGroup.style.display = 'none';
    dpAmountGroup.style.display = 'block';
  }

  const pmMode = document.getElementById('pm-mode').value;
  const pmPercentGroup = document.getElementById('pm-percent-group');
  const pmAmountGroup = document.getElementById('pm-amount-group');

  if (pmMode === 'percent') {
    pmPercentGroup.style.display = 'block';
    pmAmountGroup.style.display = 'none';
  } else {
    pmPercentGroup.style.display = 'none';
    pmAmountGroup.style.display = 'block';
  }

  const overrideTax = document.getElementById('override-tax-rate').checked;
  const overrideMortgage = document.getElementById('override-mortgage-rate').checked;
  const taxRateGroup = document.getElementById('tax-rate-group');
  const mortgageRateGroup = document.getElementById('mortgage-rate-group');

  taxRateGroup.style.display = overrideTax ? 'block' : 'none';
  mortgageRateGroup.style.display = overrideMortgage ? 'block' : 'none';
}

async function saveFormData() {
  const prefs = {
    downPaymentMode: document.getElementById('dp-mode').value,
    downPaymentPercent: parseFloat(document.getElementById('down-payment-percent').value) || DEFAULT_PREFERENCES.downPaymentPercent,
    downPaymentAmount: parseFloat(document.getElementById('down-payment-amount').value) || DEFAULT_PREFERENCES.downPaymentAmount,
    insuranceMonthly: parseFloat(document.getElementById('insurance-monthly').value) || DEFAULT_PREFERENCES.insuranceMonthly,
    hoaMonthly: parseFloat(document.getElementById('hoa-monthly').value) || DEFAULT_PREFERENCES.hoaMonthly,
    propertyManagementMode: document.getElementById('pm-mode').value,
    propertyManagementPercent: parseFloat(document.getElementById('pm-percent').value) || DEFAULT_PREFERENCES.propertyManagementPercent,
    propertyManagementAmount: parseFloat(document.getElementById('pm-amount').value) || DEFAULT_PREFERENCES.propertyManagementAmount,
    overrideTaxRate: document.getElementById('override-tax-rate').checked,
    overrideMortgageRate: document.getElementById('override-mortgage-rate').checked,
    propertyTaxRateAnnualPct: document.getElementById('override-tax-rate').checked
      ? parseFloat(document.getElementById('tax-rate').value) || null
      : null,
    mortgageRateAnnualPct: document.getElementById('override-mortgage-rate').checked
      ? parseFloat(document.getElementById('mortgage-rate').value) || null
      : null,
    enabledSites: {
      redfin: document.getElementById('enable-redfin').checked,
      zillow: document.getElementById('enable-zillow').checked,
    },
  };

  await savePreferences(prefs);
}

function showMessage(message) {
  const msg = document.createElement('div');
  msg.textContent = message;
  msg.style.cssText = `
    position: fixed;
    top: 16px;
    right: 16px;
    background: #0a0a0a;
    color: white;
    padding: 8px 16px;
    border-radius: 4px;
    font-size: 12px;
    z-index: 10000;
  `;
  document.body.appendChild(msg);
  setTimeout(() => msg.remove(), 2000);
}


// Custom Line Items Management
let currentEditingItemId = null;
let customLineItems = [];

function renderCustomItems() {
  const container = document.getElementById('custom-items-list');
  if (!container) return;

  if (customLineItems.length === 0) {
    container.innerHTML = '<p style="font-size: 12px; color: #737373; text-align: center; padding: 12px 0;">No custom expenses added yet</p>';
    return;
  }

  container.innerHTML = customLineItems.map(item => {
    let details = '';
    if (item.method === 'amount') {
      details = `$${item.value.toFixed(2)}/month`;
    } else {
      const percentOfLabel = 
        item.percentOf === 'purchasePrice' ? 'Purchase Price' :
        item.percentOf === 'rent' ? 'Monthly Rent' :
        item.percentOf === 'downPayment' ? 'Down Payment' : '';
      details = `${item.value}% of ${percentOfLabel}`;
    }

    return `
      <div class="custom-item">
        <div class="custom-item-info">
          <div class="custom-item-label">${item.label}</div>
          <div class="custom-item-details">${details}</div>
        </div>
        <div class="custom-item-actions">
          <button type="button" class="icon-btn edit" data-id="${item.id}">Edit</button>
          <button type="button" class="icon-btn delete" data-id="${item.id}">Delete</button>
        </div>
      </div>
    `;
  }).join('');

  // Attach event listeners
  container.querySelectorAll('.edit').forEach(btn => {
    btn.addEventListener('click', () => editCustomItem(btn.dataset.id));
  });
  container.querySelectorAll('.delete').forEach(btn => {
    btn.addEventListener('click', () => deleteCustomItem(btn.dataset.id));
  });
}

function openCustomItemModal(itemId = null) {
  const modal = document.getElementById('custom-item-modal');
  const form = document.getElementById('custom-item-form');
  const titleEl = document.getElementById('modal-title');

  currentEditingItemId = itemId;

  if (itemId) {
    titleEl.textContent = 'Edit Custom Expense';
    const item = customLineItems.find(i => i.id === itemId);
    if (item) {
      document.getElementById('custom-item-label').value = item.label;
      document.getElementById('custom-item-method').value = item.method;
      document.getElementById('custom-item-value').value = item.value;
      if (item.method === 'percent') {
        document.getElementById('custom-item-percent-of').value = item.percentOf || 'purchasePrice';
      }
      updateCustomItemMethodUI();
    }
  } else {
    titleEl.textContent = 'Add Custom Expense';
    form.reset();
    updateCustomItemMethodUI();
  }

  modal.style.display = 'flex';
}

function closeCustomItemModal() {
  document.getElementById('custom-item-modal').style.display = 'none';
  document.getElementById('custom-item-form').reset();
  currentEditingItemId = null;
}

function updateCustomItemMethodUI() {
  const method = document.getElementById('custom-item-method').value;
  const percentOfGroup = document.getElementById('custom-item-percent-of-group');
  const valueLabel = document.getElementById('custom-item-value-label');

  if (method === 'percent') {
    percentOfGroup.style.display = 'block';
    valueLabel.textContent = 'Percentage (%)';
  } else {
    percentOfGroup.style.display = 'none';
    valueLabel.textContent = 'Amount ($)';
  }
}

function saveCustomItem(e) {
  e.preventDefault();

  const label = document.getElementById('custom-item-label').value;
  const method = document.getElementById('custom-item-method').value;
  const value = parseFloat(document.getElementById('custom-item-value').value);
  const percentOf = method === 'percent' ? document.getElementById('custom-item-percent-of').value : undefined;

  const newItem = {
    id: currentEditingItemId || Date.now().toString(),
    label,
    method,
    value,
    percentOf,
  };

  if (currentEditingItemId) {
    // Edit existing
    const index = customLineItems.findIndex(i => i.id === currentEditingItemId);
    if (index !== -1) {
      customLineItems[index] = newItem;
    }
  } else {
    // Add new
    customLineItems.push(newItem);
  }

  // Save to storage
  chrome.storage.sync.set({ customLineItems }, () => {
    renderCustomItems();
    closeCustomItemModal();
    showMessage('Custom expense saved');
  });
}

function editCustomItem(itemId) {
  openCustomItemModal(itemId);
}

function deleteCustomItem(itemId) {
  if (!confirm('Are you sure you want to delete this custom expense?')) {
    return;
  }

  customLineItems = customLineItems.filter(i => i.id !== itemId);
  chrome.storage.sync.set({ customLineItems }, () => {
    renderCustomItems();
    showMessage('Custom expense deleted');
  });
}

// Initialize custom items event listeners
function initCustomItems() {
  document.getElementById('add-custom-item-btn')?.addEventListener('click', () => openCustomItemModal());
  document.getElementById('modal-close-btn')?.addEventListener('click', closeCustomItemModal);
  document.getElementById('modal-cancel-btn')?.addEventListener('click', closeCustomItemModal);
  document.getElementById('custom-item-form')?.addEventListener('submit', saveCustomItem);
  document.getElementById('custom-item-method')?.addEventListener('change', updateCustomItemMethodUI);

  // Load custom items from storage
  chrome.storage.sync.get(['customLineItems'], (items) => {
    customLineItems = items.customLineItems || [];
    renderCustomItems();
  });
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    init();
    initCustomItems();
  });
} else {
  init();
  initCustomItems();
}

